version: '3.8'

networks:
  app_network:
    name: ${APP_NAME}_network

services:
  nginx_service:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}_nginx-container
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - ./app:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_service
    links:
      - "php_service:php_fpm"
    networks:
      - app_network

  # php
  php_service:
    image: foxmark/php8.2.12-fpm:${PHP_IMAGE_VERSION}
    container_name: ${APP_NAME}_php_container
    user: "${UID}:${GID}"
    volumes:
      - ./app:/app
      - ./docker/php/config/99-php.ini:/usr/local/etc/php/conf.d/99-php.ini
    networks:
      - app_network
