version: '3.8'

networks:
  app-network:
    name: ${APP_NAME}-network

services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}-nginx-container
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - ./app:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-service
    links:
      - "php-service:php-fpm"
    networks:
      - app-network

  # php
  php-service:
    image: foxmark/php8.2.12-fpm:1.0
    container_name: ${APP_NAME}-php-container
    # to add whole env file
    # env_file:
    #   - .env
    volumes:
      - ./app:/app
      - ./docker/php/config/99-php.ini:/usr/local/etc/php/conf.d/99-php.ini
    networks:
      - app-network
