version: '3.8'

networks:
  app_network:
    name: ${APP_NAME}_network

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - ./app:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    links:
      - "php:php_fpm"
    networks:
      - app_network

  php:
    image: foxmark/php8.2.12-fpm:${PHP_IMAGE_VERSION}
    volumes:
      - ./app:/app
      - ./docker/php/config/99-php.ini:/usr/local/etc/php/conf.d/99-php.ini
    networks:
      - app_network
